<p style="font-family: Calibri; font-size:3.75em;color:dodgerblue; font-style:bold"><br>
Datasets exploration</p><br>

Datasets from https://data.worldbank.org/data-catalog:
* World Development Indicators [September 2017]
* Education Statistics [June 2017]
* Gender Statistics [October 2017]

*idea: can life expectancy be predicted by certain economic indicators?
Is this different for males and females?
Is this different for developed and developing countries?* 
Check link: 
https://www.weforum.org/agenda/2016/10/the-relationship-between-gdp-and-life-expectancy-isnt-as-simple-as-you-might-think

check: http://hamelg.blogspot.com.au/2015/11/python-for-data-analysis-part-14.html

check: http://hamelg.blogspot.com.au/2015/11/python-for-data-analysis-part-15.html

check: http://hamelg.blogspot.com.au/2015/11/python-for-data-analysis-part-28.html

<p style="font-family: Calibri; font-size:2.00em;color:seagreen; font-style:bold">
Import libraries</p>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

<p style="font-family: Calibri; font-size:2.00em;color:seagreen; font-style:bold">
Ingest data</p>

**Note: there are multiple datasets in each folder, explore which one(s) is/are needed**

In [2]:
# World Development Indicators (WDI)
wdi_raw = pd.read_csv('./World_Bank_Data/wdi_csv/wdidata.csv')

In [3]:
# Education Statistics (EdStats)
edstats_raw = pd.read_csv('./World_Bank_Data/edstats_csv/edstatsdata.csv')

In [4]:
# Gender Statistics (GenderStats)
genderstats_raw = pd.read_csv('./World_Bank_Data/gender_stats_csv/gender_statsdata.csv')

<p style="font-family: Calibri; font-size:2.00em;color:seagreen; font-style:bold">
First explorations of the data</p>
<p style="font-family: Calibri; font-size:1.50em;color:hotpink; font-style:bold">
World Development Indicators dataset</p>

In [5]:
# Check the dimensions
wdi_raw.shape

(409992, 63)

In [6]:
# Check the variables and their datatypes
wdi_raw.dtypes

Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960              float64
1961              float64
1962              float64
1963              float64
1964              float64
1965              float64
1966              float64
1967              float64
1968              float64
1969              float64
1970              float64
1971              float64
1972              float64
1973              float64
1974              float64
1975              float64
1976              float64
1977              float64
1978              float64
1979              float64
1980              float64
1981              float64
1982              float64
1983              float64
1984              float64
1985              float64
                   ...
1989              float64
1990              float64
1991              float64
1992              float64
1993              float64
1994              float64
1995              float64
1996              float64
1997              float64
1998              float64
1999              float64
2000              float64
2001              float64
2002              float64
2003              float64
2004              float64
2005              float64
2006              float64
2007              float64
2008              float64
2009              float64
2010              float64
2011              float64
2012              float64
2013              float64
2014              float64
2015              float64
2016              float64
2017              float64
Unnamed: 62       float64
Length: 63, dtype: object

In [7]:
# Investigate 10 random rows
wdi_raw.sample(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 62
27459,IDA blend,IDB,"Population ages 10-14, male (% of male populat...",SP.POP.1014.MA.5Y,11.035315,10.956144,10.912436,10.902178,10.926832,10.984829,...,1.186652e+01,1.177714e+01,1.166298e+01,1.155887e+01,1.146567e+01,1.139572e+01,1.136132e+01,11.358116,NaN,NaN
340256,Slovak Republic,SVK,Broad money (current LCU),FM.LBL.BMNY.CN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214957,Iraq,IRQ,"Imports of goods and services (BoP, current US$)",BM.GSR.GNFS.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.384790e+10,4.719150e+10,5.175700e+10,6.344600e+10,6.510510e+10,5.999050e+10,4.580780e+10,NaN,NaN,NaN
95615,Bahrain,BHR,"Net bilateral aid flows from DAC donors, New Z...",DC.DAC.NZLL.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122994,Cabo Verde,CPV,CPIA structural policies cluster average (1=lo...,IQ.CPA.STRC.XQ,NaN,NaN,NaN,NaN,NaN,NaN,...,3.833333e+00,3.833333e+00,4.000000e+00,4.000000e+00,4.000000e+00,3.833333e+00,3.833330e+00,3.833333,NaN,NaN
52044,Not classified,INX,"Manufacturing, value added (constant LCU)",NV.IND.MANF.KN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151463,Curacao,CUW,Merchandise imports from low- and middle-incom...,TM.VAL.MRCH.R2.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127411,Canada,CAN,Agricultural land (% of land area),AG.LND.AGRI.ZS,NaN,7.678553,7.692629,7.706705,7.720671,7.734857,...,7.031410e+00,6.957555e+00,6.883701e+00,7.197001e+00,7.186554e+00,7.176107e+00,NaN,NaN,NaN,NaN
83477,Antigua and Barbuda,ATG,"PPG, multilateral (INT, current US$)",DT.INT.MLAT.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88038,Aruba,ABW,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,6.438867,6.552130,6.658446,6.765023,6.865447,6.955965,...,5.641408e+00,5.372950e+00,5.274409e+00,5.190474e+00,5.157745e+00,5.232994e+00,5.437829e+00,5.781473,NaN,NaN

In [8]:
# Statistical summary of dataset
wdi_raw.describe()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 62
count,3.893600e+04,4.281700e+04,4.499000e+04,4.503700e+04,4.555600e+04,4.845700e+04,4.811800e+04,4.984400e+04,4.945700e+04,5.117400e+04,...,2.173080e+05,2.279070e+05,2.206720e+05,2.215520e+05,2.145040e+05,2.175470e+05,1.878920e+05,1.164010e+05,1.650000e+04,0.0
mean,1.938190e+11,1.887850e+11,1.879963e+11,1.889742e+11,1.988597e+11,2.021878e+11,2.125014e+11,2.183213e+11,2.470170e+11,2.623145e+11,...,1.529792e+12,1.709922e+12,2.001126e+12,2.176126e+12,2.510345e+12,2.666785e+12,3.119251e+12,4.093220e+12,9.421999e+08,NaN
std,6.996941e+12,7.107462e+12,7.222192e+12,7.128523e+12,7.374747e+12,7.449346e+12,7.821626e+12,8.124236e+12,9.121915e+12,9.796674e+12,...,5.799426e+13,6.787248e+13,7.879605e+13,8.687831e+13,1.008382e+14,1.113936e+14,1.249514e+14,1.463978e+14,1.399005e+10,NaN
min,-8.181071e+13,-9.465063e+13,-1.071675e+14,-1.181558e+14,-1.319199e+14,-1.555435e+14,-1.778706e+14,-2.055397e+14,-2.332403e+14,-2.810371e+14,...,-1.962196e+14,-1.827709e+14,-2.168927e+14,-2.431930e+14,-2.853262e+14,-3.543931e+14,-3.783220e+14,-4.200882e+14,0.000000e+00,NaN
25%,4.501750e+00,4.816482e+00,4.735856e+00,4.960914e+00,5.114307e+00,4.971585e+00,5.214180e+00,5.094572e+00,5.397644e+00,4.992705e+00,...,5.280000e+00,5.313166e+00,5.718085e+00,5.232573e+00,5.422377e+00,5.254699e+00,5.090534e+00,4.219900e+00,1.000000e+01,NaN
50%,4.009875e+01,4.059600e+01,3.992906e+01,4.015044e+01,4.134063e+01,4.317400e+01,4.400000e+01,4.534439e+01,4.615512e+01,4.424449e+01,...,4.899368e+01,4.677661e+01,4.966000e+01,4.879452e+01,4.956587e+01,4.868176e+01,4.928739e+01,4.726470e+01,4.087230e+01,NaN
75%,4.377432e+05,3.600000e+05,2.530890e+05,2.941100e+05,3.500000e+05,5.803700e+05,7.351988e+05,7.201500e+05,1.000000e+06,8.981000e+05,...,1.640000e+06,8.553505e+05,1.510000e+06,1.250000e+06,2.049223e+06,9.329695e+05,5.950000e+06,5.282200e+07,1.060000e+02,NaN
max,5.507039e+14,5.823178e+14,5.930440e+14,5.797774e+14,6.002418e+14,6.067340e+14,6.236700e+14,6.322792e+14,7.012936e+14,7.491379e+14,...,6.497584e+15,6.864133e+15,7.831726e+15,8.649662e+15,9.621569e+15,1.105813e+16,1.153172e+16,1.240681e+16,6.885528e+11,NaN

In [9]:
# Number of countries included in dataset
print(len(wdi_raw["Country Name"].unique()))

264

In [10]:
# Get a summary of categorical variables
# We can get a summary of the categorical variables by passing only those columns to describe():
categorical = wdi_raw.dtypes[wdi_raw.dtypes == "object"].index
print(wdi_raw[categorical])

       Country Name Country Code  \
0        Arab World          ARB
1        Arab World          ARB
2        Arab World          ARB
3        Arab World          ARB
4        Arab World          ARB
5        Arab World          ARB
6        Arab World          ARB
7        Arab World          ARB
8        Arab World          ARB
9        Arab World          ARB
10       Arab World          ARB
11       Arab World          ARB
12       Arab World          ARB
13       Arab World          ARB
14       Arab World          ARB
15       Arab World          ARB
16       Arab World          ARB
17       Arab World          ARB
18       Arab World          ARB
19       Arab World          ARB
20       Arab World          ARB
21       Arab World          ARB
22       Arab World          ARB
23       Arab World          ARB
24       Arab World          ARB
25       Arab World          ARB
26       Arab World          ARB
27       Arab World          ARB
28       Arab World          ARB
29       Arab World          ARB
...             ...          ...
409962     Zimbabwe          ZWE
409963     Zimbabwe          ZWE
409964     Zimbabwe          ZWE
409965     Zimbabwe          ZWE
409966     Zimbabwe          ZWE
409967     Zimbabwe          ZWE
409968     Zimbabwe          ZWE
409969     Zimbabwe          ZWE
409970     Zimbabwe          ZWE
409971     Zimbabwe          ZWE
409972     Zimbabwe          ZWE
409973     Zimbabwe          ZWE
409974     Zimbabwe          ZWE
409975     Zimbabwe          ZWE
409976     Zimbabwe          ZWE
409977     Zimbabwe          ZWE
409978     Zimbabwe          ZWE
409979     Zimbabwe          ZWE
409980     Zimbabwe          ZWE
409981     Zimbabwe          ZWE
409982     Zimbabwe          ZWE
409983     Zimbabwe          ZWE
409984     Zimbabwe          ZWE
409985     Zimbabwe          ZWE
409986     Zimbabwe          ZWE
409987     Zimbabwe          ZWE
409988     Zimbabwe          ZWE
409989     Zimbabwe          ZWE
409990     Zimbabwe          ZWE
409991     Zimbabwe          ZWE

                                           Indicator Name  \
0       2005 PPP conversion factor, GDP (LCU per inter...
1       2005 PPP conversion factor, private consumptio...
2       Access to clean fuels and technologies for coo...
3                 Access to electricity (% of population)
4       Access to electricity, rural (% of rural popul...
5       Access to electricity, urban (% of urban popul...
6                                Account (% age 15+) [ts]
7          Account at a financial institution (% age 15+)
8       Account at a financial institution, female (% ...
9       Account at a financial institution, income, po...
10      Account at a financial institution, income, ri...
11      Account at a financial institution, male (% ag...
12                       Account, female (% age 15+) [ts]
13         Account, income, poorest 40% (% ages 15+) [ts]
14         Account, income, richest 60% (% ages 15+) [ts]
15                         Account, male (% age 15+) [ts]
16                Account, older adults (% ages 25+) [ts]
17      Account, primary education or less (% ages 15+...
18      Account, secondary education or more (% ages 1...
19              Account, young adults (% ages 15-24) [ts]
20      Adequacy of social insurance programs (% of to...
21      Adequacy of social protection and labor progra...
22      Adequacy of social safety net programs (% of t...
23      Adequacy of unemployment benefits and ALMP (% ...
24      Adjusted net enrollment rate, primary (% of pr...
25      Adjusted net enrollment rate, primary, female ...
26      Adjusted net enrollment rate, primary, male (%...
27         Adjusted net national income (annual % growth)
28       Adjusted net national income (constant 2010 US$)
29             Adjusted net national income (current US$)
...                                                   ...
409962  Urban land area where elevation is below 5 met...
409963  Urban land area where elevation is below 5 met...
409964                                   Urban population
409965                      Urban population (% of total)
409966                 Urban population growth (annual %)
409967  Urban population living in areas where elevati...
409968    Urban poverty gap at national poverty lines (%)
409969  Urban poverty headcount ratio at national pove...
409970               Use of IMF credit (DOD, current US$)
409971  Use of insecticide-treated bed nets (% of unde...
409972  Value lost due to electrical outages (% of sales)
409973  Vitamin A supplementation coverage rate (% of ...
409974  Vulnerable employment, female (% of female emp...
409975  Vulnerable employment, male (% of male employm...
409976  Vulnerable employment, total (% of total emplo...
409977  Wage and salaried workers, female (% of female...
409978  Wage and salaried workers, male (% of male emp...
409979  Wage and salaried workers, total (% of total e...
409980           Wanted fertility rate (births per woman)
409981  Water productivity, total (constant 2010 US$ G...
409982                 Wholesale price index (2010 = 100)
409983  Women participating in the three decisions (ow...
409984  Women who believe a husband is justified in be...
409985  Women who believe a husband is justified in be...
409986  Women who believe a husband is justified in be...
409987  Women who believe a husband is justified in be...
409988  Women who believe a husband is justified in be...
409989  Women who believe a husband is justified in be...
409990  Women who were first married by age 18 (% of w...
409991  Women's share of population ages 15+ living wi...

                  Indicator Code
0                  PA.NUS.PPP.05
1              PA.NUS.PRVT.PP.05
2                 EG.CFT.ACCS.ZS
3                 EG.ELC.ACCS.ZS
4              EG.ELC.ACCS.RU.ZS
5              EG.ELC.ACCS.UR.ZS
6                   WP_time_10.1
7                   WP_time_01.1
8                   WP_time_01.3
9                   WP_time_01.8
10                  WP_time_01.9
11                  WP_time_01.2
12                  WP_time_10.3
13                  WP_time_10.8
14                  WP_time_10.9
15                  WP_time_10.2
16                  WP_time_10.5
17                  WP_time_10.6
18                  WP_time_10.7
19                  WP_time_10.4
20      per_si_allsi.adq_pop_tot
21         per_allsp.adq_pop_tot
22      per_sa_allsa.adq_pop_tot
23      per_lm_alllm.adq_pop_tot
24                   SE.PRM.TENR
25                SE.PRM.TENR.FE
26                SE.PRM.TENR.MA
27             NY.ADJ.NNTY.KD.ZG
28                NY.ADJ.NNTY.KD
29                NY.ADJ.NNTY.CD
...                          ...
409962         AG.LND.EL5M.UR.ZS
409963         AG.LND.EL5M.UR.K2
409964               SP.URB.TOTL
409965         SP.URB.TOTL.IN.ZS
409966               SP.URB.GROW
409967         EN.POP.EL5M.UR.ZS
409968               SI.POV.URGP
409969               SI.POV.URHC
409970            DT.DOD.DIMF.CD
409971            SH.MLR.NETS.ZS
409972            IC.FRM.OUTG.ZS
409973            SN.ITK.VITA.ZS
409974         SL.EMP.VULN.FE.ZS
409975         SL.EMP.VULN.MA.ZS
409976            SL.EMP.VULN.ZS
409977         SL.EMP.WORK.FE.ZS
409978         SL.EMP.WORK.MA.ZS
409979            SL.EMP.WORK.ZS
409980               SP.DYN.WFRT
409981         ER.GDP.FWTL.M3.KD
409982               FP.WPI.TOTL
409983         SG.DMK.ALLD.FN.ZS
409984            SG.VAW.REAS.ZS
409985            SG.VAW.ARGU.ZS
409986            SG.VAW.BURN.ZS
409987            SG.VAW.GOES.ZS
409988            SG.VAW.NEGL.ZS
409989            SG.VAW.REFU.ZS
409990         SP.M18.2024.FE.ZS
409991         SH.DYN.AIDS.FE.ZS

[409992 rows x 4 columns]

In [11]:
# Explore the indicators
wdi_raw["Indicator Name"].unique().tolist()

['2005 PPP conversion factor, GDP (LCU per international $)',
 '2005 PPP conversion factor, private consumption (LCU per international $)',
 'Access to clean fuels and technologies for cooking  (% of population)',
 'Access to electricity (% of population)',
 'Access to electricity, rural (% of rural population)',
 'Access to electricity, urban (% of urban population)',
 'Account (% age 15+) [ts]',
 'Account at a financial institution (% age 15+)',
 'Account at a financial institution, female (% age 15+)',
 'Account at a financial institution, income, poorest 40% (% ages 15+)',
 'Account at a financial institution, income, richest 60% (% ages 15+)',
 'Account at a financial institution, male (% age 15+)',
 'Account, female (% age 15+) [ts]',
 'Account, income, poorest 40% (% ages 15+) [ts]',
 'Account, income, richest 60% (% ages 15+) [ts]',
 'Account, male (% age 15+) [ts]',
 'Account, older adults (% ages 25+) [ts]',
 'Account, primary education or less (% ages 15+) [ts]',
 'Account, secondary education or more (% ages 15+) [ts]',
 'Account, young adults (% ages 15-24) [ts]',
 'Adequacy of social insurance programs (% of total welfare of beneficiary households)',
 'Adequacy of social protection and labor programs (% of total welfare of beneficiary households)',
 'Adequacy of social safety net programs (% of total welfare of beneficiary households)',
 'Adequacy of unemployment benefits and ALMP (% of total welfare of beneficiary households)',
 'Adjusted net enrollment rate, primary (% of primary school age children)',
 'Adjusted net enrollment rate, primary, female (% of primary school age children)',
 'Adjusted net enrollment rate, primary, male (% of primary school age children)',
 'Adjusted net national income (annual % growth)',
 'Adjusted net national income (constant 2010 US$)',
 'Adjusted net national income (current US$)',
 'Adjusted net national income per capita (annual % growth)',
 'Adjusted net national income per capita (constant 2010 US$)',
 'Adjusted net national income per capita (current US$)',
 'Adjusted net savings, excluding particulate emission damage (% of GNI)',
 'Adjusted net savings, excluding particulate emission damage (current US$)',
 'Adjusted net savings, including particulate emission damage (% of GNI)',
 'Adjusted net savings, including particulate emission damage (current US$)',
 'Adjusted savings: carbon dioxide damage (% of GNI)',
 'Adjusted savings: carbon dioxide damage (current US$)',
 'Adjusted savings: consumption of fixed capital (% of GNI)',
 'Adjusted savings: consumption of fixed capital (current US$)',
 'Adjusted savings: education expenditure (% of GNI)',
 'Adjusted savings: education expenditure (current US$)',
 'Adjusted savings: energy depletion (% of GNI)',
 'Adjusted savings: energy depletion (current US$)',
 'Adjusted savings: gross savings (% of GNI)',
 'Adjusted savings: mineral depletion (% of GNI)',
 'Adjusted savings: mineral depletion (current US$)',
 'Adjusted savings: natural resources depletion (% of GNI)',
 'Adjusted savings: net forest depletion (% of GNI)',
 'Adjusted savings: net forest depletion (current US$)',
 'Adjusted savings: net national savings (% of GNI)',
 'Adjusted savings: net national savings (current US$)',
 'Adjusted savings: particulate emission damage (% of GNI)',
 'Adjusted savings: particulate emission damage (current US$)',
 'Adolescent fertility rate (births per 1,000 women ages 15-19)',
 'Adolescents out of school (% of lower secondary school age)',
 'Adolescents out of school, female (% of female lower secondary school age)',
 'Adolescents out of school, male (% of male lower secondary school age)',
 'Adults (ages 15+) and children (ages 0-14) newly infected with HIV',
 'Adults (ages 15+) newly infected with HIV',
 'Age dependency ratio (% of working-age population)',
 'Age dependency ratio, old (% of working-age population)',
 'Age dependency ratio, young (% of working-age population)',
 'Agricultural irrigated land (% of total agricultural land)',
 'Agricultural land (% of land area)',
 'Agricultural land (sq. km)',
 'Agricultural machinery, tractors',
 'Agricultural machinery, tractors per 100 sq. km of arable land',
 'Agricultural methane emissions (% of total)',
 'Agricultural methane emissions (thousand metric tons of CO2 equivalent)',
 'Agricultural nitrous oxide emissions (% of total)',
 'Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent)',
 'Agricultural raw materials exports (% of merchandise exports)',
 'Agricultural raw materials imports (% of merchandise imports)',
 'Agriculture value added per worker (constant 2010 US$)',
 'Agriculture, value added (% of GDP)',
 'Agriculture, value added (annual % growth)',
 'Agriculture, value added (constant 2010 US$)',
 'Agriculture, value added (constant LCU)',
 'Agriculture, value added (current LCU)',
 'Agriculture, value added (current US$)',
 'Air transport, freight (million ton-km)',
 'Air transport, passengers carried',
 'Air transport, registered carrier departures worldwide',
 'All education staff compensation, primary (% of total expenditure in primary public institutions)',
 'All education staff compensation, secondary (% of total expenditure in secondary public institutions)',
 'All education staff compensation, tertiary (% of total expenditure in tertiary public institutions)',
 'All education staff compensation, total (% of total expenditure in public institutions)',
 'Alternative and nuclear energy (% of total energy use)',
 'Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)',
 'Annual freshwater withdrawals, domestic (% of total freshwater withdrawal)',
 'Annual freshwater withdrawals, industry (% of total freshwater withdrawal)',
 'Annual freshwater withdrawals, total (% of internal resources)',
 'Annual freshwater withdrawals, total (billion cubic meters)',
 'Annualized average growth rate in per capita real survey mean consumption or income, bottom 40% of population (%)',
 'Annualized average growth rate in per capita real survey mean consumption or income, total population (%)',
 'Antiretroviral therapy coverage (% of people living with HIV)',
 'Antiretroviral therapy coverage for PMTCT (% of pregnant women living with HIV)',
 'Aquaculture production (metric tons)',
 'Arable land (% of land area)',
 'Arable land (hectares per person)',
 'Arable land (hectares)',
 'ARI treatment (% of children under 5 taken to a health provider)',
 'Armed forces personnel (% of total labor force)',
 'Armed forces personnel, total',
 'Arms exports (SIPRI trend indicator values)',
 'Arms imports (SIPRI trend indicator values)',
 'Automated teller machines (ATMs) (per 100,000 adults)',
 'Average grace period on new external debt commitments (years)',
 'Average grace period on new external debt commitments, official (years)',
 'Average grace period on new external debt commitments, private (years)',
 'Average grant element on new external debt commitments (%)',
 'Average grant element on new external debt commitments, official (%)',
 'Average grant element on new external debt commitments, private (%)',
 'Average interest on new external debt commitments (%)',
 'Average interest on new external debt commitments, official (%)',
 'Average interest on new external debt commitments, private (%)',
 'Average maturity on new external debt commitments (years)',
 'Average maturity on new external debt commitments, official (years)',
 'Average maturity on new external debt commitments, private (years)',
 'Average precipitation in depth (mm per year)',
 'Average time to clear exports through customs (days)',
 'Average working hours of children, study and work, ages 7-14 (hours per week)',
 'Average working hours of children, study and work, female, ages 7-14 (hours per week)',
 'Average working hours of children, study and work, male, ages 7-14 (hours per week)',
 'Average working hours of children, working only, ages 7-14 (hours per week)',
 'Average working hours of children, working only, female, ages 7-14 (hours per week)',
 'Average working hours of children, working only, male, ages 7-14 (hours per week)',
 'Bank capital to assets ratio (%)',
 'Bank liquid reserves to bank assets ratio (%)',
 'Bank nonperforming loans to total gross loans (%)',
 'Battle-related deaths (number of people)',
 'Benefit incidence of social insurance programs to poorest quintile (% of total social insurance benefits)',
 'Benefit incidence of social protection and labor programs to poorest quintile (% of total SPL benefits)',
 'Benefit incidence of social safety net programs to poorest quintile (% of total safety net benefits)',
 'Benefit incidence of unemployment benefits and ALMP to poorest quintile (% of total U/ALMP benefits)',
 'Binding coverage, all products (%)',
 'Binding coverage, manufactured products (%)',
 'Binding coverage, primary products (%)',
 'Bird species, threatened',
 'Birth rate, crude (per 1,000 people)',
 'Births attended by skilled health staff (% of total)',
 'Borrowers from commercial banks (per 1,000 adults)',
 'Bound rate, simple mean, all products (%)',
 'Bound rate, simple mean, manufactured products (%)',
 'Bound rate, simple mean, primary products (%)',
 'Bribery incidence (% of firms experiencing at least one bribe payment request)',
 'Broad money (% of GDP)',
 'Broad money (current LCU)',
 'Broad money growth (annual %)',
 'Broad money to total reserves ratio',
 'Burden of customs procedure, WEF (1=extremely inefficient to 7=extremely efficient)',
 'Business extent of disclosure index (0=less disclosure to 10=more disclosure)',
 'Capture fisheries production (metric tons)',
 'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)',
 'Cause of death, by injury (% of total)',
 'Cause of death, by non-communicable diseases (% of total)',
 'Central government debt, total (% of GDP)',
 'Central government debt, total (current LCU)',
 'Cereal production (metric tons)',
 'Cereal yield (kg per hectare)',
 'Changes in inventories (constant LCU)',
 'Changes in inventories (current LCU)',
 'Changes in inventories (current US$)',
 'Charges for the use of intellectual property, payments (BoP, current US$)',
 'Charges for the use of intellectual property, receipts (BoP, current US$)',
 'Chemicals (% of value added in manufacturing)',
 'Child employment in agriculture (% of economically active children ages 7-14)',
 'Child employment in agriculture, female (% of female economically active children ages 7-14)',
 'Child employment in agriculture, male (% of male economically active children ages 7-14)',
 'Child employment in manufacturing (% of economically active children ages 7-14)',
 'Child employment in manufacturing, female (% of female economically active children ages 7-14)',
 'Child employment in manufacturing, male (% of male economically active children ages 7-14)',
 'Child employment in services (% of economically active children ages 7-14)',
 'Child employment in services, female (% of female economically active children ages 7-14)',
 'Child employment in services, male (% of male economically active children ages 7-14)',
 'Children (0-14) living with HIV',
 'Children (ages 0-14) newly infected with HIV',
 'Children in employment, female (% of female children ages 7-14)',
 'Children in employment, male (% of male children ages 7-14)',
 'Children in employment, self-employed (% of children in employment, ages 7-14)',
 'Children in employment, self-employed, female (% of female children in employment, ages 7-14)',
 'Children in employment, self-employed, male (% of male children in employment, ages 7-14)',
 'Children in employment, study and work (% of children in employment, ages 7-14)',
 'Children in employment, study and work, female (% of female children in employment, ages 7-14)',
 'Children in employment, study and work, male (% of male children in employment, ages 7-14)',
 'Children in employment, total (% of children ages 7-14)',
 'Children in employment, unpaid family workers (% of children in employment, ages 7-14)',
 'Children in employment, unpaid family workers, female (% of female children in employment, ages 7-14)',
 'Children in employment, unpaid family workers, male (% of male children in employment, ages 7-14)',
 'Children in employment, wage workers (% of children in employment, ages 7-14)',
 'Children in employment, wage workers, female (% of female children in employment, ages 7-14)',
 'Children in employment, wage workers, male (% of male children in employment, ages 7-14)',
 'Children in employment, work only (% of children in employment, ages 7-14)',
 'Children in employment, work only, female (% of female children in employment, ages 7-14)',
 'Children in employment, work only, male (% of male children in employment, ages 7-14)',
 'Children out of school (% of primary school age)',
 'Children out of school, female (% of female primary school age)',
 'Children out of school, male (% of male primary school age)',
 'Children out of school, primary',
 'Children out of school, primary, female',
 'Children out of school, primary, male',
 'Children with fever receiving antimalarial drugs (% of children under age 5 with fever)',
 'Claims on central government (annual growth as % of broad money)',
 'Claims on central government, etc. (% GDP)',
 'Claims on other sectors of the domestic economy (% of GDP)',
 'Claims on other sectors of the domestic economy (annual growth as % of broad money)',
 'Claims on private sector (annual growth as % of broad money)',
 'CO2 emissions (kg per 2010 US$ of GDP)',
 'CO2 emissions (kg per 2011 PPP $ of GDP)',
 'CO2 emissions (kg per PPP $ of GDP)',
 'CO2 emissions (kt)',
 'CO2 emissions (metric tons per capita)',
 'CO2 emissions from electricity and heat production, total (% of total fuel combustion)',
 'CO2 emissions from gaseous fuel consumption (% of total)',
 'CO2 emissions from gaseous fuel consumption (kt)',
 'CO2 emissions from liquid fuel consumption (% of total)',
 'CO2 emissions from liquid fuel consumption (kt)',
 'CO2 emissions from manufacturing industries and construction (% of total fuel combustion)',
 'CO2 emissions from other sectors, excluding residential buildings and commercial and public services (% of total fuel combustion)',
 'CO2 emissions from residential buildings and commercial and public services (% of total fuel combustion)',
 'CO2 emissions from solid fuel consumption (% of total)',
 'CO2 emissions from solid fuel consumption (kt)',
 'CO2 emissions from transport (% of total fuel combustion)',
 'CO2 intensity (kg per kg of oil equivalent energy use)',
 'Coal rents (% of GDP)',
 'Combustible renewables and waste (% of total energy)',
 'Commercial bank branches (per 100,000 adults)',
 'Commercial banks and other lending (PPG + PNG) (NFL, current US$)',
 'Commercial service exports (current US$)',
 'Commercial service imports (current US$)',
 'Commitments, IBRD (COM, current US$)',
 'Commitments, IDA (COM, current US$)',
 'Commitments, official creditors (COM, current US$)',
 'Commitments, private creditors (COM, current US$)',
 'Commitments, public and publicly guaranteed (COM, current US$)',
 'Communications, computer, etc. (% of service exports, BoP)',
 'Communications, computer, etc. (% of service imports, BoP)',
 'Community health workers (per 1,000 people)',
 'Compensation of employees (% of expense)',
 'Compensation of employees (current LCU)',
 'Completeness of birth registration (%)',
 'Completeness of birth registration, rural (%)',
 'Completeness of birth registration, urban (%)',
 'Completeness of death registration with cause-of-death information (%)',
 'Completeness of infant death reporting (% of reported infant deaths to estimated infant deaths)',
 'Completeness of total death reporting (% of reported total deaths to estimated total deaths)',
 'Compulsory education, duration (years)',
 'Computer, communications and other services (% of commercial service exports)',
 'Computer, communications and other services (% of commercial service imports)',
 'Concessional debt (% of total external debt)',
 'Condom use, population ages 15-24, female (% of females ages 15-24)',
 'Condom use, population ages 15-24, male (% of males ages 15-24)',
 'Consumer price index (2010 = 100)',
 'Consumption of iodized salt (% of households)',
 'Container port traffic (TEU: 20 foot equivalent units)',
 'Contraceptive prevalence, any methods (% of women ages 15-49)',
 'Contraceptive prevalence, modern methods (% of women ages 15-49)',
 'Contributing family workers, female (% of female employment)',
 'Contributing family workers, male (% of male employment)',
 'Contributing family workers, total (% of total employment)',
 'Cost of business start-up procedures (% of GNI per capita)',
 'Cost of business start-up procedures, female (% of GNI per capita)',
 'Cost of business start-up procedures, male (% of GNI per capita)',
 'Cost to export (US$ per container)',
 'Cost to export, border compliance (US$)',
 'Cost to export, documentary compliance (US$)',
 'Cost to import (US$ per container)',
 'Cost to import, border compliance (US$)',
 'Cost to import, documentary compliance (US$)',
 'Coverage of social insurance programs (% of population)',
 'Coverage of social insurance programs in 2nd quintile (% of population)',
 'Coverage of social insurance programs in 3rd quintile (% of population)',
 'Coverage of social insurance programs in 4th quintile (% of population)',
 'Coverage of social insurance programs in poorest quintile (% of population)',
 'Coverage of social insurance programs in richest quintile (% of population)',
 'Coverage of social protection and labor programs (% of population)',
 'Coverage of social safety net programs (% of population)',
 'Coverage of social safety net programs in 2nd quintile (% of population)',
 'Coverage of social safety net programs in 3rd quintile (% of population)',
 'Coverage of social safety net programs in 4th quintile (% of population)',
 'Coverage of social safety net programs in poorest quintile (% of population)',
 'Coverage of social safety net programs in richest quintile (% of population)',
 'Coverage of unemployment benefits and ALMP (% of population)',
 'Coverage of unemployment benefits and ALMP in 2nd quintile (% of population)',
 'Coverage of unemployment benefits and ALMP in 3rd quintile (% of population)',
 'Coverage of unemployment benefits and ALMP in 4th quintile (% of population)',
 'Coverage of unemployment benefits and ALMP in poorest quintile (% of population)',
 'Coverage of unemployment benefits and ALMP in richest quintile (% of population)',
 'CPIA building human resources rating (1=low to 6=high)',
 'CPIA business regulatory environment rating (1=low to 6=high)',
 'CPIA debt policy rating (1=low to 6=high)',
 'CPIA economic management cluster average (1=low to 6=high)',
 'CPIA efficiency of revenue mobilization rating (1=low to 6=high)',
 'CPIA equity of public resource use rating (1=low to 6=high)',
 'CPIA financial sector rating (1=low to 6=high)',
 'CPIA fiscal policy rating (1=low to 6=high)',
 'CPIA gender equality rating (1=low to 6=high)',
 'CPIA macroeconomic management rating (1=low to 6=high)',
 'CPIA policies for social inclusion/equity cluster average (1=low to 6=high)',
 'CPIA policy and institutions for environmental sustainability rating (1=low to 6=high)',
 'CPIA property rights and rule-based governance rating (1=low to 6=high)',
 'CPIA public sector management and institutions cluster average (1=low to 6=high)',
 'CPIA quality of budgetary and financial management rating (1=low to 6=high)',
 'CPIA quality of public administration rating (1=low to 6=high)',
 'CPIA social protection rating (1=low to 6=high)',
 'CPIA structural policies cluster average (1=low to 6=high)',
 'CPIA trade rating (1=low to 6=high)',
 'CPIA transparency, accountability, and corruption in the public sector rating (1=low to 6=high)',

In [12]:
# Explore any indicators related to GDP

gdp_indicators = wdi_raw["Indicator Name"].str.lower().str.contains("gdp")

wdi_raw[gdp_indicators]["Indicator Name"].unique()

array(['2005 PPP conversion factor, GDP (LCU per international $)',
       'Agriculture, value added (% of GDP)', 'Broad money (% of GDP)',
       'Central government debt, total (% of GDP)',
       'Claims on central government, etc. (% GDP)',
       'Claims on other sectors of the domestic economy (% of GDP)',
       'CO2 emissions (kg per 2010 US$ of GDP)',
       'CO2 emissions (kg per 2011 PPP $ of GDP)',
       'CO2 emissions (kg per PPP $ of GDP)', 'Coal rents (% of GDP)',
       'Current account balance (% of GDP)',
       'Discrepancy in expenditure estimate of GDP (constant LCU)',
       'Discrepancy in expenditure estimate of GDP (current LCU)',
       'Domestic credit provided by financial sector (% of GDP)',
       'Domestic credit to private sector (% of GDP)',
       'Domestic credit to private sector by banks (% of GDP)',
       'Energy intensity level of primary energy (MJ/$2011 PPP GDP)',
       'Energy use (kg of oil equivalent) per $1,000 GDP (constant 2011 PPP)',
       'Expense (% of GDP)', 'Exports of goods and services (% of GDP)',
       'External balance on goods and services (% of GDP)',
       'Final consumption expenditure, etc. (% of GDP)',
       'Foreign direct investment, net inflows (% of GDP)',
       'Foreign direct investment, net outflows (% of GDP)',
       'Forest rents (% of GDP)', 'GDP (constant 2010 US$)',
       'GDP (constant LCU)', 'GDP (current LCU)', 'GDP (current US$)',
       'GDP deflator (base year varies by country)',
       'GDP deflator: linked series (base year varies by country)',
       'GDP growth (annual %)', 'GDP per capita (constant 2010 US$)',
       'GDP per capita (constant LCU)', 'GDP per capita (current LCU)',
       'GDP per capita (current US$)', 'GDP per capita growth (annual %)',
       'GDP per capita, PPP (constant 2011 international $)',
       'GDP per capita, PPP (current international $)',
       'GDP per person employed (constant 2011 PPP $)',
       'GDP per unit of energy use (constant 2011 PPP $ per kg of oil equivalent)',
       'GDP per unit of energy use (PPP $ per kg of oil equivalent)',
       'GDP, PPP (constant 2011 international $)',
       'GDP, PPP (current international $)',
       'GDP: linked series (current LCU)',
       'General government final consumption expenditure (% of GDP)',
       'Government expenditure on education, total (% of GDP)',
       'Government expenditure per student, primary (% of GDP per capita)',
       'Government expenditure per student, secondary (% of GDP per capita)',
       'Government expenditure per student, tertiary (% of GDP per capita)',
       'Gross capital formation (% of GDP)',
       'Gross domestic savings (% of GDP)',
       'Gross fixed capital formation (% of GDP)',
       'Gross fixed capital formation, private sector (% of GDP)',
       'Gross national expenditure (% of GDP)', 'Gross savings (% of GDP)',
       'Health expenditure, private (% of GDP)',
       'Health expenditure, public (% of GDP)',
       'Health expenditure, total (% of GDP)',
       'Household final consumption expenditure, etc. (% of GDP)',
       'Imports of goods and services (% of GDP)',
       'Industry, value added (% of GDP)',
       'Inflation, GDP deflator (annual %)',
       'Inflation, GDP deflator: linked series (annual %)',
       'Manufacturing, value added (% of GDP)',
       'Market capitalization of listed domestic companies (% of GDP)',
       'Merchandise trade (% of GDP)', 'Military expenditure (% of GDP)',
       'Mineral rents (% of GDP)', 'Natural gas rents (% of GDP)',
       'Net acquisition of financial assets (% of GDP)',
       'Net incurrence of liabilities, total (% of GDP)',
       'Net investment in nonfinancial assets (% of GDP)',
       'Net lending (+) / net borrowing (-) (% of GDP)',
       'Oil rents (% of GDP)', 'Personal remittances, received (% of GDP)',
       'PPP conversion factor, GDP (LCU per international $)',
       'Price level ratio of PPP conversion factor (GDP) to market exchange rate',
       'Research and development expenditure (% of GDP)',
       'Revenue, excluding grants (% of GDP)',
       'Services, etc., value added (% of GDP)',
       'Stocks traded, total value (% of GDP)', 'Tax revenue (% of GDP)',
       'Total natural resources rents (% of GDP)', 'Trade (% of GDP)',
       'Trade in services (% of GDP)',
       'Water productivity, total (constant 2010 US$ GDP per cubic meter of total freshwater withdrawal)'], dtype=object)

In [13]:
# Explore any indicators related to life expectancy

life_indicators = wdi_raw["Indicator Name"].str.lower().str.contains("life|expectancy")

wdi_raw[life_indicators]["Indicator Name"].unique()

array(['Life expectancy at birth, female (years)',
       'Life expectancy at birth, male (years)',
       'Life expectancy at birth, total (years)',
       'Lifetime risk of maternal death (%)',
       'Lifetime risk of maternal death (1 in: rate varies by country)'], dtype=object)

<p style="font-family: Calibri; font-size:1.50em;color:hotpink; font-style:bold">
Education Statistics</p>

In [14]:
# Check the dimensions
edstats_raw.shape

(886930, 70)

In [15]:
# Investigate 10 random rows
edstats_raw.sample(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1970,1971,1972,1973,1974,1975,...,2060,2065,2070,2075,2080,2085,2090,2095,2100,Unnamed: 69
408923,Hungary,HUN,PIAAC: Distribution of Adult Literacy Scores: ...,LO.PIAAC.LIT.P75,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194766,Brunei Darussalam,BRN,Cumulative drop-out rate to the last grade of ...,SE.PRM.DROP.FE.ZS,NaN,NaN,NaN,NaN,NaN,29.142981,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
434576,Isle of Man,IMN,PIAAC: Distribution of Adult Literacy Scores: ...,LO.PIAAC.LIT.P50,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187879,Brazil,BRA,EGRA: Oral Reading Fluency - Share of students...,LO.EGRA.CWPM.ZERO.AMH.3GRD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
821197,Turkmenistan,TKM,Barro-Lee: Average years of tertiary schooling...,BAR.TER.SCHL.75UP.FE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518777,"Macao SAR, China",MAC,Percentage of students enrolled in Education p...,UIS.FEP.56.F140,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229439,Central African Republic,CAF,PISA: 15-year-olds by mathematics proficiency ...,LO.PISA.MAT.1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90995,World,WLD,TIMSS: Female 4th grade students who did not r...,LO.TIMSS.SCI4.BL.FE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
401501,Honduras,HND,Percentage of students enrolled in primary edu...,UIS.OAEP.1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502429,Libya,LBY,Barro-Lee: Percentage of female population age...,BAR.TER.ICMP.4044.FE.ZS,0.05,NaN,NaN,NaN,NaN,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# Check the variables and their datatypes
edstats_raw.dtypes

Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1970              float64
1971              float64
1972              float64
1973              float64
1974              float64
1975              float64
1976              float64
1977              float64
1978              float64
1979              float64
1980              float64
1981              float64
1982              float64
1983              float64
1984              float64
1985              float64
1986              float64
1987              float64
1988              float64
1989              float64
1990              float64
1991              float64
1992              float64
1993              float64
1994              float64
1995              float64
                   ...
2006              float64
2007              float64
2008              float64
2009              float64
2010              float64
2011              float64
2012              float64
2013              float64
2014              float64
2015              float64
2016              float64
2017              float64
2020              float64
2025              float64
2030              float64
2035              float64
2040              float64
2045              float64
2050              float64
2055              float64
2060              float64
2065              float64
2070              float64
2075              float64
2080              float64
2085              float64
2090              float64
2095              float64
2100              float64
Unnamed: 69       float64
Length: 70, dtype: object

In [17]:
# Number of countries included in dataset
print(len(edstats_raw["Country Name"].unique()))

242

In [18]:
# Explore the indicators
edstats_raw["Indicator Name"].unique().tolist()

['Adjusted net enrolment rate, lower secondary, both sexes (%)',
 'Adjusted net enrolment rate, lower secondary, female (%)',
 'Adjusted net enrolment rate, lower secondary, gender parity index (GPI)',
 'Adjusted net enrolment rate, lower secondary, male (%)',
 'Adjusted net enrolment rate, primary, both sexes (%)',
 'Adjusted net enrolment rate, primary, female (%)',
 'Adjusted net enrolment rate, primary, gender parity index (GPI)',
 'Adjusted net enrolment rate, primary, male (%)',
 'Adjusted net enrolment rate, upper secondary, both sexes (%)',
 'Adjusted net enrolment rate, upper secondary, female (%)',
 'Adjusted net enrolment rate, upper secondary, gender parity index (GPI)',
 'Adjusted net enrolment rate, upper secondary, male (%)',
 'Adjusted net intake rate to Grade 1 of primary education, both sexes (%)',
 'Adjusted net intake rate to Grade 1 of primary education, female (%)',
 'Adjusted net intake rate to Grade 1 of primary education, gender parity index (GPI)',
 'Adjusted net intake rate to Grade 1 of primary education, male (%)',
 'Adult illiterate population, 15+ years, % female',
 'Adult illiterate population, 15+ years, both sexes (number)',
 'Adult illiterate population, 15+ years, female (number)',
 'Adult illiterate population, 15+ years, male (number)',
 'Adult literacy rate, population 15+ years, both sexes (%)',
 'Adult literacy rate, population 15+ years, female (%)',
 'Adult literacy rate, population 15+ years, gender parity index (GPI)',
 'Adult literacy rate, population 15+ years, male (%)',
 'Africa Dataset: Average number of grades per multigrade class in primary schools (number of grades)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 1 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 2 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 3 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 4 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 5 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 6 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 7 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 1 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 2 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 3 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 4 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 5 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 6 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 7 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in primary education (number)',
 'Africa Dataset: Average size of classes in primary schools (number of pupils)',
 'Africa Dataset: Average size of multigrade classes in primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 1 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 2 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 3 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 4 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 5 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 6 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 7 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in primary schools (number of pupils)',
 'Africa Dataset: Graduates from accredited pre-service lower secondary teacher training programmes, both sexes (number)',
 'Africa Dataset: Graduates from accredited pre-service lower secondary teacher training programmes, female (number)',
 'Africa Dataset: Graduates from accredited pre-service primary or secondary teacher training programmes, both sexes (number)',
 'Africa Dataset: Graduates from accredited pre-service primary or secondary teacher training programmes, female (number)',
 'Africa Dataset: Graduates from accredited pre-service primary teacher training programmes, both sexes (number)',
 'Africa Dataset: Graduates from accredited pre-service primary teacher training programmes, female (number)',
 'Africa Dataset: Graduates from accredited pre-service teacher training programmes, level unspecified, both sexes (number)',
 'Africa Dataset: Graduates from accredited pre-service teacher training programmes, level unspecified, female (number)',
 'Africa Dataset: Graduates from accredited pre-service upper secondary teacher training programmes, both sexes (number)',
 'Africa Dataset: Graduates from accredited pre-service upper secondary teacher training programmes, female (number)',
 'Africa Dataset: Percentage of female newly recruited teachers in lower secondary education who are trained, female (%)',
 'Africa Dataset: Percentage of female newly recruited teachers in primary education who are trained, female (%)',
 'Africa Dataset: Percentage of female newly recruited teachers in upper secondary education who are trained, female (%)',
 'Africa Dataset: Percentage of female teachers in lower secondary education who are newly recruited, female (%)',
 'Africa Dataset: Percentage of female teachers in primary education who are newly recruited, female (%)',
 'Africa Dataset: Percentage of female teachers in upper secondary education who are newly recruited, female (%)',
 'Africa Dataset: Percentage of lower secondary schools with access to electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools with access to potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools with mixed-sex toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with single-sex toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools without access to electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools without access to potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools without toilets (%)',
 'Africa Dataset: Percentage of male newly recruited teachers in lower secondary education who are trained, male (%)',
 'Africa Dataset: Percentage of male newly recruited teachers in primary education who are trained, male (%)',
 'Africa Dataset: Percentage of male newly recruited teachers in upper secondary education who are trained, male (%)',
 'Africa Dataset: Percentage of male teachers in lower secondary education who are newly recruited, male (%)',
 'Africa Dataset: Percentage of male teachers in primary education who are newly recruited, male (%)',
 'Africa Dataset: Percentage of male teachers in upper secondary education who are newly recruited, male (%)',
 'Africa Dataset: Percentage of newly recruited teachers in lower secondary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in lower secondary education who are trained, both sexes (%)',
 'Africa Dataset: Percentage of newly recruited teachers in primary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in primary education who are trained, both sexes (%)',
 'Africa Dataset: Percentage of newly recruited teachers in upper secondary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in upper secondary education who are trained, both sexes (%)',
 'Africa Dataset: Percentage of primary pupils in multigrade classes (%)',
 'Africa Dataset: Percentage of primary schools with access to electricity (%)',
 'Africa Dataset: Percentage of primary schools with access to potable water (%)',
 'Africa Dataset: Percentage of primary schools with mixed-sex toilets (%)',
 'Africa Dataset: Percentage of primary schools with no information on electricity (%)',
 'Africa Dataset: Percentage of primary schools with no information on potable water (%)',
 'Africa Dataset: Percentage of primary schools with no information on toilets (%)',
 'Africa Dataset: Percentage of primary schools with single-sex toilets (%)',
 'Africa Dataset: Percentage of primary schools with toilets (%)',
 'Africa Dataset: Percentage of primary schools without access to electricity (%)',
 'Africa Dataset: Percentage of primary schools without access to potable water (%)',
 'Africa Dataset: Percentage of primary schools without toilets (%)',
 'Africa Dataset: Percentage of teachers in lower secondary education who are newly recruited, both sexes (%)',
 'Africa Dataset: Percentage of teachers in primary education who are newly recruited, both sexes (%)',
 'Africa Dataset: Percentage of teachers in upper secondary education who are newly recruited, both sexes (%)',
 'Africa Dataset: Ratio of teacher training graduates to teachers in lower secondary education, both sexes',
 'Africa Dataset: Ratio of teacher training graduates to teachers in lower secondary education, female',
 'Africa Dataset: Ratio of teacher training graduates to teachers in lower secondary education, male',
 'Africa Dataset: Ratio of teacher training graduates to teachers in primary education, both sexes',
 'Africa Dataset: Ratio of teacher training graduates to teachers in primary education, female',
 'Africa Dataset: Ratio of teacher training graduates to teachers in primary education, male',
 'Africa Dataset: Ratio of teacher training graduates to teachers in upper secondary education, both sexes',
 'Africa Dataset: Ratio of teacher training graduates to teachers in upper secondary education, female',
 'Africa Dataset: Ratio of teacher training graduates to teachers in upper secondary education, male',
 'Africa Dataset: School census return rate from primary schools',
 'Africa Dataset: School census return rate from secondary schools',
 'Africa Dataset: Teacher attrition rate from public lower secondary education, both sexes (%)',
 'Africa Dataset: Teacher attrition rate from public lower secondary education, female (%)',
 'Africa Dataset: Teacher attrition rate from public lower secondary education, male (%)',
 'Africa Dataset: Teacher attrition rate from public primary education, both sexes (%)',
 'Africa Dataset: Teacher attrition rate from public primary education, female (%)',
 'Africa Dataset: Teacher attrition rate from public primary education, male (%)',
 'Africa Dataset: Teacher attrition rate from public upper secondary education, both sexes (%)',
 'Africa Dataset: Teacher attrition rate from public upper secondary education, female (%)',
 'Africa Dataset: Teacher attrition rate from public upper secondary education, male (%)',
 'All staff compensation as % of total expenditure in lower secondary public institutions (%)',
 'All staff compensation as % of total expenditure in post-secondary non-tertiary public institutions (%)',
 'All staff compensation as % of total expenditure in pre-primary public institutions (%)',
 'All staff compensation as % of total expenditure in primary public institutions (%)',
 'All staff compensation as % of total expenditure in public institutions (%)',
 'All staff compensation as % of total expenditure in secondary public institutions (%)',
 'All staff compensation as % of total expenditure in tertiary public institutions (%)',
 'All staff compensation as % of total expenditure in upper secondary public institutions (%)',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. Top of scale',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. Top of scale',
 'Annual statutory teacher salaries in public institutions in USD. Primary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Primary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Primary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Primary. Top of scale',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. Top of scale',
 'Barro-Lee: Average years of primary schooling, age 15+, female',
 'Barro-Lee: Average years of primary schooling, age 15+, total',
 'Barro-Lee: Average years of primary schooling, age 15-19, female',
 'Barro-Lee: Average years of primary schooling, age 15-19, total',
 'Barro-Lee: Average years of primary schooling, age 20-24, female',
 'Barro-Lee: Average years of primary schooling, age 20-24, total',
 'Barro-Lee: Average years of primary schooling, age 25+, female',
 'Barro-Lee: Average years of primary schooling, age 25+, total',
 'Barro-Lee: Average years of primary schooling, age 25-29, female',
 'Barro-Lee: Average years of primary schooling, age 25-29, total',
 'Barro-Lee: Average years of primary schooling, age 30-34, female',
 'Barro-Lee: Average years of primary schooling, age 30-34, total',
 'Barro-Lee: Average years of primary schooling, age 35-39, female',
 'Barro-Lee: Average years of primary schooling, age 35-39, total',
 'Barro-Lee: Average years of primary schooling, age 40-44, female',
 'Barro-Lee: Average years of primary schooling, age 40-44, total',
 'Barro-Lee: Average years of primary schooling, age 45-49, female',
 'Barro-Lee: Average years of primary schooling, age 45-49, total',
 'Barro-Lee: Average years of primary schooling, age 50-54, female',
 'Barro-Lee: Average years of primary schooling, age 50-54, total',
 'Barro-Lee: Average years of primary schooling, age 55-59, female',
 'Barro-Lee: Average years of primary schooling, age 55-59, total',
 'Barro-Lee: Average years of primary schooling, age 60-64, female',
 'Barro-Lee: Average years of primary schooling, age 60-64, total',
 'Barro-Lee: Average years of primary schooling, age 65-69, female',
 'Barro-Lee: Average years of primary schooling, age 65-69, total',
 'Barro-Lee: Average years of primary schooling, age 70-74, female',
 'Barro-Lee: Average years of primary schooling, age 70-74, total',
 'Barro-Lee: Average years of primary schooling, age 75+, female',
 'Barro-Lee: Average years of primary schooling, age 75+, total',
 'Barro-Lee: Average years of secondary schooling, age 15+, female',
 'Barro-Lee: Average years of secondary schooling, age 15+, total',
 'Barro-Lee: Average years of secondary schooling, age 15-19, female',
 'Barro-Lee: Average years of secondary schooling, age 15-19, total',
 'Barro-Lee: Average years of secondary schooling, age 20-24, female',
 'Barro-Lee: Average years of secondary schooling, age 20-24, total',
 'Barro-Lee: Average years of secondary schooling, age 25+, female',
 'Barro-Lee: Average years of secondary schooling, age 25+, total',
 'Barro-Lee: Average years of secondary schooling, age 25-29, female',
 'Barro-Lee: Average years of secondary schooling, age 25-29, total',
 'Barro-Lee: Average years of secondary schooling, age 30-34, female',
 'Barro-Lee: Average years of secondary schooling, age 30-34, total',
 'Barro-Lee: Average years of secondary schooling, age 35-39, female',
 'Barro-Lee: Average years of secondary schooling, age 35-39, total',
 'Barro-Lee: Average years of secondary schooling, age 40-44, female',
 'Barro-Lee: Average years of secondary schooling, age 40-44, total',
 'Barro-Lee: Average years of secondary schooling, age 45-49, female',
 'Barro-Lee: Average years of secondary schooling, age 45-49, total',
 'Barro-Lee: Average years of secondary schooling, age 50-54, female',
 'Barro-Lee: Average years of secondary schooling, age 50-54, total',
 'Barro-Lee: Average years of secondary schooling, age 55-59, female',
 'Barro-Lee: Average years of secondary schooling, age 55-59, total',
 'Barro-Lee: Average years of secondary schooling, age 60-64, female',
 'Barro-Lee: Average years of secondary schooling, age 60-64, total',
 'Barro-Lee: Average years of secondary schooling, age 65-69, female',
 'Barro-Lee: Average years of secondary schooling, age 65-69, total',
 'Barro-Lee: Average years of secondary schooling, age 70-74, female',
 'Barro-Lee: Average years of secondary schooling, age 70-74, total',
 'Barro-Lee: Average years of secondary schooling, age 75+, female',
 'Barro-Lee: Average years of secondary schooling, age 75+, total',
 'Barro-Lee: Average years of tertiary schooling, age 15+, female',
 'Barro-Lee: Average years of tertiary schooling, age 15+, total',
 'Barro-Lee: Average years of tertiary schooling, age 15-19, female',
 'Barro-Lee: Average years of tertiary schooling, age 15-19, total',
 'Barro-Lee: Average years of tertiary schooling, age 20-24, female',
 'Barro-Lee: Average years of tertiary schooling, age 20-24, total',
 'Barro-Lee: Average years of tertiary schooling, age 25+, female',
 'Barro-Lee: Average years of tertiary schooling, age 25+, total',
 'Barro-Lee: Average years of tertiary schooling, age 25-29, female',
 'Barro-Lee: Average years of tertiary schooling, age 25-29, total',
 'Barro-Lee: Average years of tertiary schooling, age 30-34, female',
 'Barro-Lee: Average years of tertiary schooling, age 30-34, total',
 'Barro-Lee: Average years of tertiary schooling, age 35-39, female',
 'Barro-Lee: Average years of tertiary schooling, age 35-39, total',
 'Barro-Lee: Average years of tertiary schooling, age 40-44, female',
 'Barro-Lee: Average years of tertiary schooling, age 40-44, total',
 'Barro-Lee: Average years of tertiary schooling, age 45-49, female',
 'Barro-Lee: Average years of tertiary schooling, age 45-49, total',
 'Barro-Lee: Average years of tertiary schooling, age 50-54, female',
 'Barro-Lee: Average years of tertiary schooling, age 50-54, total',
 'Barro-Lee: Average years of tertiary schooling, age 55-59, female',
 'Barro-Lee: Average years of tertiary schooling, age 55-59, total',
 'Barro-Lee: Average years of tertiary schooling, age 60-64, female',
 'Barro-Lee: Average years of tertiary schooling, age 60-64, total',

<p style="font-family: Calibri; font-size:1.50em;color:hotpink; font-style:bold">
Gender Statistics</p>

In [19]:
genderstats_raw.shape

(165690, 63)

In [20]:
genderstats_raw.dtypes

Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960              float64
1961              float64
1962              float64
1963              float64
1964              float64
1965              float64
1966              float64
1967              float64
1968              float64
1969              float64
1970              float64
1971              float64
1972              float64
1973              float64
1974              float64
1975              float64
1976              float64
1977              float64
1978              float64
1979              float64
1980              float64
1981              float64
1982              float64
1983              float64
1984              float64
1985              float64
                   ...
1989              float64
1990              float64
1991              float64
1992              float64
1993              float64
1994              float64
1995              float64
1996              float64
1997              float64
1998              float64
1999              float64
2000              float64
2001              float64
2002              float64
2003              float64
2004              float64
2005              float64
2006              float64
2007              float64
2008              float64
2009              float64
2010              float64
2011              float64
2012              float64
2013              float64
2014              float64
2015              float64
2016              float64
2017              float64
Unnamed: 62       float64
Length: 63, dtype: object

In [21]:
# Investigate 10 random rows
genderstats_raw.sample(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 62
67258,Equatorial Guinea,GNQ,Used an account at a financial institution to ...,WP11636.2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7143,European Union,EUU,"Labor force with basic education, male (% of m...",SL.TLF.BASC.MA.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.862441e+01,4.787932e+01,4.872060e+01,4.802826e+01,4.758190e+01,4.827317e+01,4.783698e+01,NaN,NaN,NaN
36673,Azerbaijan,AZE,"Educational attainment, completed short-cycle ...",SE.TER.HIAT.ST.MA.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.337320e+00,8.340220e+00,8.340640e+00,NaN,NaN,NaN
136508,Singapore,SGP,"School enrollment, secondary, male (% gross)",SE.SEC.ENRR.MA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48810,Burundi,BDI,Men who own land jointly (% of men): Q2,SG.OWN.LDJT.MA.Q2.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.450000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3105,East Asia & Pacific,EAS,Women who do not own a house (% of women age 1...,SG.OWN.HSNO.FE.Q5.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145706,Suriname,SUR,GDP (current US$),NY.GDP.MKTP.CD,93850000.0,98400000.0,103500000.0,110000000.0,120850000.0,138650000.0,...,3.875410e+09,4.368398e+09,4.422277e+09,4.980000e+09,5.145758e+09,5.240606e+09,4.878732e+09,3.620700e+09,NaN,NaN
122697,Pakistan,PAK,Used an account at a financial institution to ...,WP11636.3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6.227533e-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97282,Latvia,LVA,Men who do not own land (% of men),SG.OWN.LDNO.MA.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123909,Panama,PAN,"School enrollment, secondary, male (% net)",SE.SEC.NENR.MA,NaN,NaN,NaN,NaN,NaN,NaN,...,6.074758e+01,6.377355e+01,6.282431e+01,7.515138e+01,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
# Number of countries included in dataset
print(len(genderstats_raw["Country Name"].unique()))

263

In [23]:
# Explore the indicators
genderstats_raw["Indicator Name"].unique().tolist()

['Access to anti-retroviral drugs, female (%)',
 'Access to anti-retroviral drugs, male (%)',
 'Account at a financial institution, female (% age 15+) [ts]',
 'Account at a financial institution, male (% age 15+) [ts]',
 'Account, female (% age 15+) [ts]',
 'Account, male (% age 15+) [ts]',
 'Adjusted net enrollment rate, primary, female (% of primary school age children)',
 'Adjusted net enrollment rate, primary, male (% of primary school age children)',
 'Adolescent fertility rate (births per 1,000 women ages 15-19)',
 'Age at first marriage, female',
 'Age at first marriage, male',
 'Age dependency ratio (% of working-age population)',
 'Age population, age 0, female, interpolated',
 'Age population, age 0, male, interpolated',
 'Age population, age 01, female, interpolated',
 'Age population, age 01, male, interpolated',
 'Age population, age 02, female, interpolated',
 'Age population, age 02, male, interpolated',
 'Age population, age 03, female, interpolated',
 'Age population, age 03, male, interpolated',
 'Age population, age 04, female, interpolated',
 'Age population, age 04, male, interpolated',
 'Age population, age 05, female, interpolated',
 'Age population, age 05, male, interpolated',
 'Average number of hours spent on unpaid domestic work (housework and child care), female',
 'Average number of hours spent on unpaid domestic work (housework and child care), male',
 'Birth rate, crude (per 1,000 people)',
 'Births attended by skilled health staff (% of total)',
 'Borrowed any money in the past year, female (% age 15+) [w2]',
 'Borrowed any money in the past year, male (% age 15+) [w2]',
 'Borrowed for education or school fees, female (% age 15+) [w2]',
 'Borrowed for education or school fees, male (% age 15+) [w2]',
 'Borrowed for health or medical purposes, female (% age 15+) [w2]',
 'Borrowed for health or medical purposes, male (% age 15+) [w2]',
 'Borrowed from a financial institution, female (% age 15+) [ts]',
 'Borrowed from a financial institution, male (% age 15+) [ts]',
 'Borrowed from a private informal lender, female (% age 15+) [ts]',
 'Borrowed from a private informal lender, male (% age 15+) [ts]',
 'Borrowed from a store by buying on credit, female (% age 15+) [w1]',
 'Borrowed from a store by buying on credit, female (% age 15+) [w2]',
 'Borrowed from a store by buying on credit, male (% age 15+) [w1]',
 'Borrowed from a store by buying on credit, male (% age 15+) [w2]',
 'Borrowed from an employer, female (% age 15+) [w1]',
 'Borrowed from an employer, male (% age 15+) [w1]',
 'Borrowed from family or friends, female (% age 15+) [ts]',
 'Borrowed from family or friends, male (% age 15+) [ts]',
 'Borrowed to start, operate, or expand a farm or business, female (% age 15+) [w2]',
 'Borrowed to start, operate, or expand a farm or business, male (% age 15+) [w2]',
 'Cause of death, by communicable diseases, ages 15-34, female (% of relevant age group)',
 'Cause of death, by communicable diseases, ages 15-34, male (% of relevant age group)',
 'Cause of death, by communicable diseases, ages 35-59, female (% of relevant age group)',
 'Cause of death, by communicable diseases, ages 35-59, male (% of relevant age group)',
 'Cause of death, by injury, ages 15-34, female  (% of relevant age group)',
 'Cause of death, by injury, ages 15-34, male (% of relevant age group)',
 'Cause of death, by injury, ages 35-59, female (% of relevant age group)',
 'Cause of death, by injury, ages 35-59, male (% of relevant age group)',
 'Cause of death, by non-communicable diseases, ages 15-34, female (% of relevant age group)',
 'Cause of death, by non-communicable diseases, ages 15-34, male (% of relevant age group)',
 'Cause of death, by non-communicable diseases, ages 35-59, female (% of relevant age group)',
 'Cause of death, by non-communicable diseases, ages 35-59, male (% of relevant age group)',
 'Children in employment, female (% of female children ages 7-14)',
 'Children in employment, male (% of male children ages 7-14)',
 'Children out of school, primary, female',
 'Children out of school, primary, male',
 'Coming up with emergency funds: not at all possible, female (% age 15+) [w2]',
 'Coming up with emergency funds: not at all possible, male (% age 15+) [w2]',
 'Coming up with emergency funds: not very possible, female (% age 15+) [w2]',
 'Coming up with emergency funds: not very possible, male (% age 15+) [w2]',
 'Coming up with emergency funds: somewhat possible, female (% age 15+) [w2]',
 'Coming up with emergency funds: somewhat possible, male (% age 15+) [w2]',
 'Coming up with emergency funds: very possible, female (% age 15+) [w2]',
 'Coming up with emergency funds: very possible, male (% age 15+) [w2]',
 'Contraceptive prevalence, any methods (% of women ages 15-49)',
 'Contraceptive prevalence, modern methods (% of women ages 15-49)',
 'Contributing family workers, female (% of female employment)',
 'Contributing family workers, male (% of male employment)',
 'Cost of business start-up procedures, female (% of GNI per capita)',
 'Cost of business start-up procedures, male (% of GNI per capita)',
 'Credit card used in the past year, female (% age 15+) [w2]',
 'Credit card used in the past year, male (% age 15+) [w2]',
 'Credit card, female (% age 15+) [ts]',
 'Credit card, male (% age 15+) [ts]',
 'Death rate, crude (per 1,000 people)',
 'Debit card in own name, female (% age 15+) [w2]',
 'Debit card in own name, male (% age 15+) [w2]',
 'Debit card used in the past year, female (% age 15+) [w2]',
 'Debit card used in the past year, male (% age 15+) [w2]',
 'Debit card, female (% age 15+) [ts]',
 'Debit card, male (% age 15+) [ts]',
 "Decision maker about a woman's own health care: mainly husband (% of women age 15-49)",
 "Decision maker about a woman's own health care: mainly wife (% of women age 15-49)",
 "Decision maker about a woman's own health care: other (% of women age 15-49)",
 "Decision maker about a woman's own health care: someone else (% of women age 15-49)",
 "Decision maker about a woman's own health care: wife and husband jointly (% of women age 15-49)",
 "Decision maker about a woman's visits to her family or relatives: mainly husband (% of women age 15-49)",
 "Decision maker about a woman's visits to her family or relatives: mainly wife (% of women age 15-49)",
 "Decision maker about a woman's visits to her family or relatives: other (% of women age 15-49)",
 "Decision maker about a woman's visits to her family or relatives: someone else (% of women age 15-49)",
 'Decision maker about major household purchases: mainly husband (% of women age 15-49)',
 'Decision maker about major household purchases: mainly wife (% of women age 15-49)',
 'Decision maker about major household purchases: other (% of women age 15-49)',
 'Decision maker about major household purchases: someone else (% of women age 15-49)',
 'Decision maker about major household purchases: wife and husband jointly (% of women age 15-49)',
 'Decision maker about Visits to her family or relatives: wife and husband jointly (% of women age 15-49)',
 'Demand for family planning satisfied by any methods (% of married women with demand for family planning)',
 'Demand for family planning satisfied by modern methods (% of married women with demand for family planning)',
 "Educational attainment, at least Bachelor's or equivalent, population 25+, female (%) (cumulative)",
 "Educational attainment, at least Bachelor's or equivalent, population 25+, male (%) (cumulative)",
 'Educational attainment, at least completed lower secondary, population 25+, female (%) (cumulative)',
 'Educational attainment, at least completed lower secondary, population 25+, male (%) (cumulative)',
 'Educational attainment, at least completed post-secondary, population 25+, female (%) (cumulative)',
 'Educational attainment, at least completed post-secondary, population 25+, male (%) (cumulative)',
 'Educational attainment, at least completed primary, population 25+ years, female (%) (cumulative)',
 'Educational attainment, at least completed primary, population 25+ years, male (%) (cumulative)',
 'Educational attainment, at least completed short-cycle tertiary, population 25+, female (%) (cumulative)',
 'Educational attainment, at least completed short-cycle tertiary, population 25+, male (%) (cumulative)',
 'Educational attainment, at least completed upper secondary, population 25+, female (%) (cumulative)',
 'Educational attainment, at least completed upper secondary, population 25+, male (%) (cumulative)',
 "Educational attainment, at least Master's or equivalent, population 25+, female (%) (cumulative)",
 "Educational attainment, at least Master's or equivalent, population 25+, male (%) (cumulative)",
 "Educational attainment, completed Bachelor's or equivalent, population 25+ years, female (%)",
 "Educational attainment, completed Bachelor's or equivalent, population 25+ years, male (%)",
 'Educational attainment, completed Doctoral or equivalent, population 25+ years, female (%)',
 'Educational attainment, completed Doctoral or equivalent, population 25+ years, male (%)',
 'Educational attainment, completed lower secondary, population 25+ years, female (%)',
 'Educational attainment, completed lower secondary, population 25+ years, male (%)',
 "Educational attainment, completed Master's or equivalent, population 25+ years, female (%)",
 "Educational attainment, completed Master's or equivalent, population 25+ years, male (%)",
 'Educational attainment, completed post-secondary, population 25+ years, female (%)',
 'Educational attainment, completed post-secondary, population 25+ years, male (%)',
 'Educational attainment, completed primary, population 25+ years, female (%)',
 'Educational attainment, completed primary, population 25+ years, male (%)',
 'Educational attainment, completed short-cycle tertiary, population 25+ years, female (%)',
 'Educational attainment, completed short-cycle tertiary, population 25+ years, male (%)',
 'Educational attainment, completed upper secondary, population 25+ years, female (%)',
 'Educational attainment, completed upper secondary, population 25+ years, male (%)',
 'Educational attainment, Doctoral or equivalent, population 25+, female (%) (cumulative)',
 'Educational attainment, Doctoral or equivalent, population 25+, male (%) (cumulative)',
 'Educational attainment, no schooling, population 25+ years, female (%)',
 'Educational attainment, no schooling, population 25+ years, male (%)',
 'Educational attainment, some primary, population 25+ years, female (%)',
 'Educational attainment, some primary, population 25+ years, male (%)',
 'Educational attainment, some primary, population 25+ years, total (%)',
 'Employers, female (% of female employment)',
 'Employers, male (% of male employment)',
 'Employment in agriculture, female (% of female employment)',
 'Employment in agriculture, male (% of male employment)',
 'Employment in industry, female (% of female employment)',
 'Employment in industry, male (% of male employment)',
 'Employment in services, female (% of female employment)',
 'Employment in services, male (% of male employment)',
 'Employment to population ratio, 15+, female (%) (modeled ILO estimate)',
 'Employment to population ratio, 15+, female (%) (national estimate)',
 'Employment to population ratio, 15+, male (%) (modeled ILO estimate)',
 'Employment to population ratio, 15+, male (%) (national estimate)',
 'Employment to population ratio, 15+, total (%) (national estimate)',
 'Employment to population ratio, ages 15-24, female (%) (modeled ILO estimate)',
 'Employment to population ratio, ages 15-24, female (%) (national estimate)',
 'Employment to population ratio, ages 15-24, male (%) (modeled ILO estimate)',
 'Employment to population ratio, ages 15-24, male (%) (national estimate)',
 'Employment to population ratio, ages 15-24, total (%) (national estimate)',
 'Expected years of schooling, female',
 'Expected years of schooling, male',
 'Female genital mutilation prevalence (%)',
 'Female genital mutilation prevalence (%): Q1 (lowest)',
 'Female genital mutilation prevalence (%): Q2',
 'Female genital mutilation prevalence (%): Q3',
 'Female genital mutilation prevalence (%): Q4',
 'Female genital mutilation prevalence (%): Q5 (highest)',
 'Female headed households (% of households with a female head)',
 'Female migrants (% of international migrant stock)',
 'Female professional and technical workers (% of total)',
 'Female share of employment in senior and middle management (%)',
 'Fertility rate, total (births per woman)',
 'Firms with female participation in ownership (% of firms)',
 'Firms with female top manager (% of firms)',
 'GDP (current US$)',
 'GDP growth (annual %)',
 'GDP per capita (Current US$)',
 'GINI index (World Bank estimate)',
 'GNI per capita, Atlas method (current US$)',
 'GNI per capita, PPP (current international $)',
 'GNI, Atlas method (current US$)',
 'Government expenditure on education, total (% of GDP)',
 'Government expenditure per student, primary (% of GDP per capita)',
 'Government expenditure per student, secondary (% of GDP per capita)',
 'Gross graduation ratio, primary, female (%)',
 'Gross graduation ratio, primary, male (%)',
 'Gross graduation ratio, tertiary, female (%)',
 'Gross graduation ratio, tertiary, male (%)',
 'Health expenditure per capita, PPP (constant 2011 international $)',
 'Health expenditure, public (% of GDP)',
 'Households with water 30 minutes or longer away round trip (%)',
 'Households with water less than 30 minutes away round trip (%)',
 'Households with water on the premises (%)',
 'Immunization, DPT (% of children ages 12-23 months)',
 'Immunization, measles (% of children ages 12-23 months)',
 'Improved sanitation facilities (% of population with access)',
 'Improved water source (% of population with access)',
 'Inflation, consumer prices (annual %)',
 'Informal employment, female (% of total non-agricultural employment)',
 'Informal employment, male (% of total non-agricultural employment)',
 'Labor force participation rate for ages 15-24, female (%) (modeled ILO estimate)',
 'Labor force participation rate for ages 15-24, female (%) (national estimate)',
 'Labor force participation rate for ages 15-24, male (%) (modeled ILO estimate)',
 'Labor force participation rate for ages 15-24, male (%) (national estimate)',
 'Labor force participation rate, female (% of female population ages 15+) (modeled ILO estimate)',
 'Labor force participation rate, female (% of female population ages 15+) (national estimate)',
 'Labor force participation rate, male (% of male population ages 15+) (modeled ILO estimate)',
 'Labor force participation rate, male (% of male population ages 15+) (national estimate)',
 'Labor force with advanced education, female (% of female working-age population with advanced education)',
 'Labor force with advanced education, male (% of male working-age population with advanced education)',
 'Labor force with basic education, female (% of female working-age population with basic education)',
 'Labor force with basic education, male (% of male working-age population with basic education)',
 'Labor force with intermediate education, female (% of female working-age population with intermediate education)',
 'Labor force with intermediate education, male (% of male working-age population with intermediate education)',
 'Labor force, female',
 'Labor force, female (% of total labor force)',
 'Labor force, total',
 'Law mandates equal remuneration for females and males for work of equal value (1=yes; 0=no)',
 'Law mandates nondiscrimination based on gender in hiring (1=yes; 0=no)',
 'Law mandates paid or unpaid maternity leave (1=yes; 0=no)',
 'Law prohibits or invalidates child or early marriage (1=yes; 0=no)',
 'Legislation exists on domestic violence (1=yes; 0=no)',
 'Legislation explicitly criminalizes marital rape (1=yes; 0=no)',
 'Legislation specifically addresses sexual harassment (1=yes; 0=no)',
 'Life expectancy at age 60, female (years)',
 'Life expectancy at age 60, male (years)',
 'Life expectancy at birth, female (years)',
 'Life expectancy at birth, male (years)',
 'Literacy rate, adult female (% of females ages 15 and above)',
 'Literacy rate, adult male (% of males ages 15 and above)',
 'Literacy rate, youth (ages 15-24), gender parity index (GPI)',
 'Literacy rate, youth female (% of females ages 15-24)',
 'Literacy rate, youth male (% of males ages 15-24)',
 'Loan in the past year, female (% age 15+)',
 'Loan in the past year, male (% age 15+)',
 'Location of cooking: inside the house (% of households)',
 'Location of cooking: other places (% of households)',
 'Location of cooking: outdoors (% of households)',
 'Location of cooking: separate building (% of households)',
 'Lower secondary completion rate, female (% of relevant age group)',
 'Lower secondary completion rate, male (% of relevant age group)',
 'Main cooking fuel: agricultural crop (% of households)',
 'Main cooking fuel: charcoal (% of households)',
 'Main cooking fuel: dung (% of households)',
 'Main cooking fuel: electricity  (% of households)',
 'Main cooking fuel: LPG/natural gas/biogas (% of households)',
 'Main cooking fuel: straw/shrubs/grass (% of households)',
 'Main cooking fuel: wood (% of households)',
 'Married men and married women have equal ownership rights to property (1=yes; 0=no)',
 'Married women are required by law to obey their husbands (1=yes; 0=no)',
 'Married women can obtain a national ID card in the same way as married men (1=yes; 0=no)',
 'Maternal mortality ratio (modeled estimate, per 100,000 live births)',
 'Maternity leave (days paid)',
 'Maternity leave benefits (% of wages paid)',
 'Men who do not own a house (% of men)',
 'Men who do not own a house (% of men): Q1 (lowest)',
 'Men who do not own a house (% of men): Q2',
 'Men who do not own a house (% of men): Q3',
 'Men who do not own a house (% of men): Q4',
 'Men who do not own a house (% of men): Q5 (highest)',
 'Men who do not own land (% of men)',
 'Men who do not own land (% of men): Q1 (lowest)',
 'Men who do not own land (% of men): Q2',
 'Men who do not own land (% of men): Q3',
 'Men who do not own land (% of men): Q4',
 'Men who do not own land (% of men): Q5 (highest)',
 'Men who own a house alone (% of men)',
 'Men who own a house alone (% of men): Q1 (lowest)',
 'Men who own a house alone (% of men): Q2',
 'Men who own a house alone (% of men): Q3',
 'Men who own a house alone (% of men): Q4',
 'Men who own a house alone (% of men): Q5 (highest)',
 'Men who own a house both alone and jointly (% of men)',
 'Men who own a house both alone and jointly (% of men): Q1 (lowest)',
 'Men who own a house both alone and jointly (% of men): Q2',
 'Men who own a house both alone and jointly (% of men): Q3',
 'Men who own a house both alone and jointly (% of men): Q4',
 'Men who own a house both alone and jointly (% of men): Q5 (highest)',
 'Men who own a house jointly (% of men)',
 'Men who own a house jointly (% of men): Q1 (lowest)',
 'Men who own a house jointly (% of men): Q2',
 'Men who own a house jointly (% of men): Q3',
 'Men who own a house jointly (% of men): Q4',
 'Men who own a house jointly (% of men): Q5 (highest)',
 'Men who own land alone (% of men)',
 'Men who own land alone (% of men): Q1 (lowest)',
 'Men who own land alone (% of men): Q2',
 'Men who own land alone (% of men): Q3',
 'Men who own land alone (% of men): Q4',
 'Men who own land alone (% of men): Q5 (highest)',
 'Men who own land both alone and jointly (% of men)',
 'Men who own land both alone and jointly (% of men): Q1 (lowest)',
 'Men who own land both alone and jointly (% of men): Q2',
 'Men who own land both alone and jointly (% of men): Q3',
 'Men who own land both alone and jointly (% of men): Q4',
 'Men who own land both alone and jointly (% of men): Q5 (highest)',
 'Men who own land jointly (% of men)',

<p style="font-family: Calibri; font-size:2.00em;color:seagreen; font-style:bold">
What data do I need for my analysis?</p>
I'll be merging the three datasets. I need to ensure that there is overlap for the indicators that I want to use with respect to countries and years, otherwise I cannot use these indicators to create a new dataset.

<p style="font-family: Calibri; font-size:1.50em;color:hotpink; font-style:bold">
World Development Indicators dataset</p>
Drop all columns and records that are not needed for my final dataset

In [24]:
gdp_per_capita = wdi_raw["Indicator Name"] == "GDP per capita (constant 2010 US$)"

len(wdi_raw[gdp_per_capita]["Country Code"].unique())

264

In [25]:
# Create a copy of the dataset that only includes rows with GDP per capita
wdi_gdp = wdi_raw[gdp_per_capita].copy()
wdi_gdp.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 62
515,Arab World,ARB,GDP per capita (constant 2010 US$),NY.GDP.PCAP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5782.422470,5916.329624,5986.728791,6153.876337,6238.020811,6282.349489,6366.423081,6440.036495,NaN,NaN
2068,Caribbean small states,CSS,GDP per capita (constant 2010 US$),NY.GDP.PCAP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,8634.456217,8701.583469,8739.038486,8792.251107,8881.021081,8867.290784,8823.230590,8613.830353,NaN,NaN
3621,Central Europe and the Baltics,CEB,GDP per capita (constant 2010 US$),NY.GDP.PCAP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,12274.776244,12556.939168,12996.183003,13100.384959,13302.291191,13721.421606,14250.790576,14701.064993,NaN,NaN
5174,Early-demographic dividend,EAR,GDP per capita (constant 2010 US$),NY.GDP.PCAP.KD,1105.450443,1125.209039,1144.841312,1176.908968,1243.242004,1277.964239,...,2782.348625,2918.784661,3029.757152,3103.986590,3192.863132,3288.524227,3392.254676,3480.884549,NaN,NaN
6727,East Asia & Pacific,EAS,GDP per capita (constant 2010 US$),NY.GDP.PCAP.KD,1276.424994,1347.374176,1412.626081,1487.663573,1608.488030,1675.197796,...,7219.847585,7677.795457,7978.507795,8294.195197,8630.136984,8924.230204,9228.102619,9542.709687,NaN,NaN

In [26]:
# Check if df only contains one indicator
wdi_gdp["Indicator Code"].unique()

array(['NY.GDP.PCAP.KD'], dtype=object)

In [27]:
wdi_gdp.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', 'Unnamed: 62'],
      dtype='object')

In [28]:
# Drop columns that are not needed - only keep data for the year 2010
# Also drop "Indicator code"

keep_columns = ["Country Name", "Country Code", "Indicator Name", "2010"]

for name in wdi_gdp.columns:
    if name not in keep_columns:
        wdi_gdp.drop(name, 1, inplace=True)

wdi_gdp.columns

Index(['Country Name', 'Country Code', 'Indicator Name', '2010'], dtype='object')

In [29]:
wdi_gdp.head()

,Country Name,Country Code,Indicator Name,2010
515,Arab World,ARB,GDP per capita (constant 2010 US$),5916.329624
2068,Caribbean small states,CSS,GDP per capita (constant 2010 US$),8701.583469
3621,Central Europe and the Baltics,CEB,GDP per capita (constant 2010 US$),12556.939168
5174,Early-demographic dividend,EAR,GDP per capita (constant 2010 US$),2918.784661
6727,East Asia & Pacific,EAS,GDP per capita (constant 2010 US$),7677.795457

In [30]:
# Drop rows with NaN values
wdi_gdp.dropna(axis=0, inplace=True)
wdi_gdp.sample(10)

,Country Name,Country Code,Indicator Name,2010
185322,Germany,DEU,GDP per capita (constant 2010 US$),41785.556913
78165,American Samoa,ASM,GDP per capita (constant 2010 US$),10352.822762
267631,Mauritania,MRT,GDP per capita (constant 2010 US$),1203.383675
116990,Brunei Darussalam,BRN,GDP per capita (constant 2010 US$),35268.101170
303350,Pakistan,PAK,GDP per capita (constant 2010 US$),1040.142268
16045,Europe & Central Asia (IDA & IBRD countries),TEC,GDP per capita (constant 2010 US$),8234.343255
138732,Colombia,COL,GDP per capita (constant 2010 US$),6250.655044
248995,Liechtenstein,LIE,GDP per capita (constant 2010 US$),141165.082857
8280,East Asia & Pacific (excluding high income),EAP,GDP per capita (constant 2010 US$),4008.175818
36234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,GDP per capita (constant 2010 US$),8861.671986

In [31]:
# Count the number of observations
wdi_gdp.shape

(249, 4)

In [32]:
# Check the number of unique countries in the analysis
len(wdi_gdp["Country Name"].unique())

249

<p style="font-family: Calibri; font-size:1.50em;color:hotpink; font-style:bold">
Education Statistics dataset</p>
Drop all columns and records that are not needed for my final dataset

In [33]:
# I have selected two potential indicators: 
# Barro-Lee: Average years of tertiary schooling, age 15+, female (BAR.TER.SCHL.15UP.FE)
# UIS: Percentage of population age 25+ with a completed bachelor's or equivalent degree (ISCED 6). Female (UIS.EA.6.AG25T99.F)

female_attainment = (edstats_raw["Indicator Code"] == "BAR.TER.SCHL.15UP.FE") | (edstats_raw["Indicator Code"] == "UIS.EA.6.AG25T99.F")

edstats_raw[female_attainment]["Indicator Code"].unique()

array(['BAR.TER.SCHL.15UP.FE', 'UIS.EA.6.AG25T99.F'], dtype=object)

In [34]:
# Create a copy of the dataset that only contains these indicators
fem_att_df = edstats_raw[female_attainment].copy()
fem_att_df.sample(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1970,1971,1972,1973,1974,1975,...,2060,2065,2070,2075,2080,2085,2090,2095,2100,Unnamed: 69
747193,Spain,ESP,UIS: Percentage of population age 25+ with a c...,UIS.EA.6.AG25T99.F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
813163,Trinidad and Tobago,TTO,UIS: Percentage of population age 25+ with a c...,UIS.EA.6.AG25T99.F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
465664,"Korea, Dem. People’s Rep.",PRK,Barro-Lee: Average years of tertiary schooling...,BAR.TER.SCHL.15UP.FE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
407024,Hungary,HUN,Barro-Lee: Average years of tertiary schooling...,BAR.TER.SCHL.15UP.FE,0.11,NaN,NaN,NaN,NaN,0.15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
545618,Malta,MLT,UIS: Percentage of population age 25+ with a c...,UIS.EA.6.AG25T99.F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
684888,Rwanda,RWA,UIS: Percentage of population age 25+ with a c...,UIS.EA.6.AG25T99.F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494984,Lesotho,LSO,Barro-Lee: Average years of tertiary schooling...,BAR.TER.SCHL.15UP.FE,0.00,NaN,NaN,NaN,NaN,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
857143,Uzbekistan,UZB,UIS: Percentage of population age 25+ with a c...,UIS.EA.6.AG25T99.F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
809498,Tonga,TON,UIS: Percentage of population age 25+ with a c...,UIS.EA.6.AG25T99.F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
629913,Norway,NOR,UIS: Percentage of population age 25+ with a c...,UIS.EA.6.AG25T99.F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
fem_att_df.shape

(484, 70)

In [36]:
fem_att_df.describe()

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,...,2060,2065,2070,2075,2080,2085,2090,2095,2100,Unnamed: 69
count,144.000000,0.0,0.0,0.0,0.0,144.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,0.069861,NaN,NaN,NaN,NaN,0.099167,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.093644,NaN,NaN,NaN,NaN,0.121675,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.010000,NaN,NaN,NaN,NaN,0.010000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.040000,NaN,NaN,NaN,NaN,0.060000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,0.100000,NaN,NaN,NaN,NaN,0.150000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,0.560000,NaN,NaN,NaN,NaN,0.690000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
# Drop columns that are not needed - only keep data for the year 2010
# Also drop "Indicator code"

keep_columns = ["Country Name", "Country Code", "Indicator Name", "2005", "2010"]

for name in fem_att_df.columns:
    if name not in keep_columns:
        fem_att_df.drop(name, 1, inplace=True)

fem_att_df.columns

Index(['Country Name', 'Country Code', 'Indicator Name', '2005', '2010'], dtype='object')

In [38]:
fem_att_df.sample(20)

,Country Name,Country Code,Indicator Name,2005,2010
3874,East Asia & Pacific,EAS,Barro-Lee: Average years of tertiary schooling...,NaN,NaN
124819,Aruba,ABW,Barro-Lee: Average years of tertiary schooling...,NaN,NaN
487654,Latvia,LVA,Barro-Lee: Average years of tertiary schooling...,0.57000,0.68000
593263,Namibia,NAM,UIS: Percentage of population age 25+ with a c...,NaN,NaN
216444,Cameroon,CMR,Barro-Lee: Average years of tertiary schooling...,0.05000,0.08000
739863,South Africa,ZAF,UIS: Percentage of population age 25+ with a c...,3.42662,5.52204
802844,Togo,TGO,Barro-Lee: Average years of tertiary schooling...,0.03000,0.05000
494308,Lebanon,LBN,UIS: Percentage of population age 25+ with a c...,NaN,NaN
135814,Azerbaijan,AZE,Barro-Lee: Average years of tertiary schooling...,NaN,NaN
102829,American Samoa,ASM,Barro-Lee: Average years of tertiary schooling...,NaN,NaN
157128,Belarus,BLR,UIS: Percentage of population age 25+ with a c...,NaN,NaN
212103,Cabo Verde,CPV,UIS: Percentage of population age 25+ with a c...,NaN,NaN
835153,Uganda,UGA,UIS: Percentage of population age 25+ with a c...,NaN,1.93607
297074,Dominican Republic,DOM,Barro-Lee: Average years of tertiary schooling...,0.32000,0.27000
736198,Somalia,SOM,UIS: Percentage of population age 25+ with a c...,NaN,NaN
348384,"Gambia, The",GMB,Barro-Lee: Average years of tertiary schooling...,0.03000,0.03000
761853,St. Martin (French part),MAF,UIS: Percentage of population age 25+ with a c...,NaN,NaN
98488,Albania,ALB,UIS: Percentage of population age 25+ with a c...,NaN,NaN
879809,Zambia,ZMB,Barro-Lee: Average years of tertiary schooling...,0.02000,0.02000
483313,Kyrgyz Republic,KGZ,UIS: Percentage of population age 25+ with a c...,NaN,NaN

In [39]:
fem_att_df.describe()

             2005        2010
count  176.000000  212.000000
mean     3.618792    6.208388
std      8.014205   10.368800
min      0.000000    0.000000
25%      0.120000    0.187500
50%      0.400000    0.660000
75%      0.862500   10.901977
max     36.005040   45.582110

In [40]:
# Drop rows with NaN values
fem_att_df.dropna(axis=0, inplace=True)
fem_att_df.sample(10)

,Country Name,Country Code,Indicator Name,2005,2010
861484,"Venezuela, RB",VEN,Barro-Lee: Average years of tertiary schooling...,0.39,0.38
564619,Moldova,MDA,Barro-Lee: Average years of tertiary schooling...,0.38,0.52
407024,Hungary,HUN,Barro-Lee: Average years of tertiary schooling...,0.57,0.69
480324,Kyrgyz Republic,KGZ,Barro-Lee: Average years of tertiary schooling...,0.45,0.54
597604,Nepal,NPL,Barro-Lee: Average years of tertiary schooling...,0.04,0.05
791849,Tanzania,TZA,Barro-Lee: Average years of tertiary schooling...,0.02,0.02
297074,Dominican Republic,DOM,Barro-Lee: Average years of tertiary schooling...,0.32,0.27
817504,Turkey,TUR,Barro-Lee: Average years of tertiary schooling...,0.18,0.24
99164,Algeria,DZA,Barro-Lee: Average years of tertiary schooling...,0.19,0.39
663574,Portugal,PRT,Barro-Lee: Average years of tertiary schooling...,0.31,0.36

In [41]:
# Count the number of observations
fem_att_df.shape

(169, 5)

In [71]:
# Check the number of unique countries in the dataframe
sorted(fem_att_df["Country Code"].unique())

['AFG',
 'ALB',
 'ARE',
 'ARG',
 'ARM',
 'AUS',
 'AUT',
 'BDI',
 'BEL',
 'BEN',
 'BGD',
 'BGR',
 'BHR',
 'BLZ',
 'BOL',
 'BRA',
 'BRB',
 'BRN',
 'BWA',
 'CAF',
 'CAN',
 'CHE',
 'CHL',
 'CHN',
 'CIV',
 'CMR',
 'COD',
 'COG',
 'COL',
 'CRI',
 'CUB',
 'CYP',
 'CZE',
 'DEU',
 'DNK',
 'DOM',
 'DZA',
 'ECU',
 'EGY',
 'ESP',
 'EST',
 'FIN',
 'FJI',
 'FRA',
 'GAB',
 'GBR',
 'GHA',
 'GMB',
 'GRC',
 'GTM',
 'GUY',
 'HKG',
 'HND',
 'HRV',
 'HTI',
 'HUN',
 'IDN',
 'IND',
 'IRL',
 'IRN',
 'IRQ',
 'ISL',
 'ISR',
 'ITA',
 'JAM',
 'JOR',
 'JPN',
 'KAZ',
 'KEN',
 'KGZ',
 'KHM',
 'KOR',
 'KWT',
 'LAO',
 'LBR',
 'LBY',
 'LKA',
 'LSO',
 'LTU',
 'LUX',
 'LVA',
 'MAC',
 'MAR',
 'MDA',
 'MDV',
 'MEX',
 'MLI',
 'MLT',
 'MMR',
 'MNG',
 'MOZ',
 'MRT',
 'MUS',
 'MWI',
 'MYS',
 'NAM',
 'NER',
 'NIC',
 'NLD',
 'NOR',
 'NPL',
 'NZL',
 'PAK',
 'PAN',
 'PER',
 'PHL',
 'PNG',
 'POL',
 'PRT',
 'PRY',
 'QAT',
 'ROU',
 'RUS',
 'RWA',
 'SAU',
 'SDN',
 'SEN',
 'SGP',
 'SLE',
 'SLV',
 'SRB',
 'SVK',
 'SVN',
 'SWE',
 'SWZ',
 'SYR',
 'TGO',
 'THA',
 'TJK',
 'TON',
 'TTO',
 'TUN',
 'TUR',
 'TZA',
 'UGA',
 'UKR',
 'URY',
 'USA',
 'VEN',
 'VNM',
 'YEM',
 'ZAF',
 'ZMB',
 'ZWE']

<p style="font-family: Calibri; font-size:1.50em;color:deeppink; font-style:bold">
Gender Statistics dataset</p>
Drop all columns and records that are not needed for my final dataset

In [59]:
# I have selected four potential indicators: 
# Firms with female top manager (% of firms) (IC.FRM.FEMM.ZS)
# Female share of employment in senior and middle management (%) (SL.EMP.SMGT.FE.ZS)
# Women who own a house both alone and jointly (% of women age 15-49) (SG.OWN.HSAJ.FE.ZS)
# Employment to population ratio, 15+, female (%) (national estimate) (SL.EMP.TOTL.SP.FE.NE.ZS)

female_participation = (genderstats_raw["Indicator Code"] == "IC.FRM.FEMM.ZS") | (genderstats_raw["Indicator Code"] == "SL.EMP.SMGT.FE.ZS") | (genderstats_raw["Indicator Code"] == "SG.OWN.HSAJ.FE.ZS") | (genderstats_raw["Indicator Code"] == "SL.EMP.TOTL.SP.FE.NE.ZS")

genderstats_raw[female_participation]["Indicator Code"].unique()

array(['SL.EMP.TOTL.SP.FE.NE.ZS', 'SL.EMP.SMGT.FE.ZS', 'IC.FRM.FEMM.ZS',
       'SG.OWN.HSAJ.FE.ZS'], dtype=object)

In [60]:
# Create a copy of the dataset that only contains these indicators
fem_part_df = genderstats_raw[female_participation].copy()
fem_part_df.sample(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 62
159988,Uruguay,URY,Women who own a house both alone and jointly (...,SG.OWN.HSAJ.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124912,Paraguay,PRY,Female share of employment in senior and middl...,SL.EMP.SMGT.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70735,Finland,FIN,Firms with female top manager (% of firms),IC.FRM.FEMM.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67582,Eritrea,ERI,Female share of employment in senior and middl...,SL.EMP.SMGT.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129952,Russian Federation,RUS,Female share of employment in senior and middl...,SL.EMP.SMGT.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33988,Argentina,ARG,Women who own a house both alone and jointly (...,SG.OWN.HSAJ.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144442,St. Vincent and the Grenadines,VCT,Female share of employment in senior and middl...,SL.EMP.SMGT.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116702,Netherlands,NLD,"Employment to population ratio, 15+, female (%...",SL.EMP.TOTL.SP.FE.NE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,58.330002,56.259998,55.580002,55.599998,54.91,53.93,54.52,NaN,NaN,NaN
75772,Gibraltar,GIB,Female share of employment in senior and middl...,SL.EMP.SMGT.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41752,Benin,BEN,Female share of employment in senior and middl...,SL.EMP.SMGT.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
fem_part_df.shape

(1052, 63)

In [62]:
fem_part_df.describe()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 62
count,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,...,216.000000,228.000000,176.000000,185.000000,230.000000,193.000000,174.000000,82.000000,0.0,0.0
mean,41.553333,41.406666,41.250000,40.986668,41.023335,41.383334,42.269999,42.806667,43.106667,43.660000,...,35.926471,37.063103,39.836689,38.945192,35.807939,38.228510,40.338313,27.991501,NaN,NaN
std,10.450039,10.490456,9.838049,8.931607,8.163732,7.436272,6.841600,6.610659,6.039085,5.109551,...,16.019476,16.332334,16.115733,16.602720,18.715282,17.295472,15.356684,17.782512,NaN,NaN
min,35.520000,35.349998,35.570000,35.830002,36.310001,37.090000,38.320000,38.990002,39.619999,40.709999,...,0.300000,0.100000,0.500000,0.000000,0.500000,0.500000,0.200000,1.400000,NaN,NaN
25%,35.520000,35.349998,35.570000,35.830002,36.310001,37.090000,38.320000,38.990002,39.619999,40.709999,...,22.207500,23.960000,29.230000,28.240000,21.270000,27.400000,29.960000,16.020690,NaN,NaN
50%,35.520000,35.349998,35.570000,35.830002,36.310001,37.090000,38.320000,38.990002,39.619999,40.709999,...,37.450001,38.570000,42.847128,42.220001,36.525000,39.790001,42.410002,20.731786,NaN,NaN
75%,44.570000,44.434999,44.090000,43.565001,43.380001,43.530001,44.244999,44.715000,44.850000,45.135000,...,47.185006,47.272499,49.582022,48.820000,48.185001,49.709999,49.990731,41.697500,NaN,NaN
max,53.619999,53.520000,52.610001,51.299999,50.450001,49.970001,50.169998,50.439999,50.080002,49.560001,...,78.419998,86.300003,85.199997,85.500000,85.599998,84.599998,85.000000,77.339996,NaN,NaN

In [63]:
# Drop columns that are not needed - only keep data for 2010
# Also drop "Indicator code"

keep_columns = ["Country Name", "Country Code", "Indicator Name", "2010"]

for name in fem_part_df.columns:
    if name not in keep_columns:
        fem_part_df.drop(name, 1, inplace=True)

fem_part_df.columns

Index(['Country Name', 'Country Code', 'Indicator Name', '2010'], dtype='object')

In [64]:
# Drop rows with NaN values
fem_part_df.dropna(axis=0, inplace=True)
fem_part_df.sample(10)

,Country Name,Country Code,Indicator Name,2010
50552,Cameroon,CMR,"Employment to population ratio, 15+, female (%...",67.209999
66325,El Salvador,SLV,Firms with female top manager (% of firms),21.400000
782,Caribbean small states,CSS,"Employment to population ratio, 15+, female (%...",46.365307
162062,Vietnam,VNM,"Employment to population ratio, 15+, female (%...",70.800003
39235,Barbados,BRB,Firms with female top manager (% of firms),25.400000
129322,Romania,ROU,Female share of employment in senior and middl...,36.279999
85222,Indonesia,IDN,Female share of employment in senior and middl...,20.110001
90242,Japan,JPN,"Employment to population ratio, 15+, female (%...",46.250000
34802,Aruba,ABW,"Employment to population ratio, 15+, female (%...",53.310001
120482,Northern Mariana Islands,MNP,"Employment to population ratio, 15+, female (%...",57.880001

In [65]:
fem_part_df.shape

(228, 4)

In [69]:
# Check number of unique countries in df
sorted((fem_part_df['Country Code'].unique()))

['ABW',
 'AGO',
 'ALB',
 'ARG',
 'ARM',
 'ATG',
 'AUS',
 'AUT',
 'AZE',
 'BDI',
 'BEL',
 'BEN',
 'BFA',
 'BGD',
 'BGR',
 'BHR',
 'BHS',
 'BIH',
 'BLR',
 'BLZ',
 'BMU',
 'BOL',
 'BRA',
 'BRB',
 'BTN',
 'BWA',
 'CAN',
 'CEB',
 'CHE',
 'CHL',
 'CMR',
 'COD',
 'COL',
 'CRI',
 'CSS',
 'CYM',
 'CYP',
 'CZE',
 'DEU',
 'DMA',
 'DNK',
 'DOM',
 'DZA',
 'EAR',
 'ECA',
 'ECS',
 'ECU',
 'EGY',
 'EMU',
 'ESP',
 'EST',
 'ETH',
 'EUU',
 'FIN',
 'FRA',
 'FRO',
 'GAB',
 'GBR',
 'GEO',
 'GHA',
 'GRC',
 'GRD',
 'GTM',
 'GUM',
 'GUY',
 'HIC',
 'HKG',
 'HND',
 'HRV',
 'HUN',
 'IDN',
 'IND',
 'IRL',
 'IRN',
 'ISL',
 'ISR',
 'ITA',
 'JAM',
 'JOR',
 'JPN',
 'KGZ',
 'KHM',
 'KIR',
 'KNA',
 'KOR',
 'KWT',
 'LAC',
 'LBR',
 'LCA',
 'LCN',
 'LIE',
 'LKA',
 'LMC',
 'LTU',
 'LUX',
 'LVA',
 'MAC',
 'MAR',
 'MDA',
 'MDG',
 'MDV',
 'MEA',
 'MEX',
 'MKD',
 'MLI',
 'MLT',
 'MNA',
 'MNE',
 'MNP',
 'MUS',
 'MYS',
 'NAC',
 'NIC',
 'NLD',
 'NOR',
 'NZL',
 'OED',
 'OMN',
 'PAK',
 'PAN',
 'PER',
 'PHL',
 'POL',
 'PRT',
 'PRY',
 'PSE',
 'PST',
 'QAT',
 'ROU',
 'RUS',
 'RWA',
 'SAS',
 'SGP',
 'SLV',
 'SRB',
 'SUR',
 'SVK',
 'SVN',
 'SWE',
 'SYR',
 'TEC',
 'THA',
 'TLA',
 'TMN',
 'TSA',
 'TTO',
 'TUN',
 'TUR',
 'UKR',
 'URY',
 'USA',
 'VCT',
 'VEN',
 'VNM',
 'YEM',
 'ZAF']